# Generated by Django 2.2 on 2021-03-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_auto_20210312_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='dob',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
