# Generated by Django 2.2 on 2021-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0006_auto_20210313_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
